version: '3.4'

services:
  ci-build:
    image: microsoft/dotnet:2.1-runtime
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./AspNetCore.Identity.Cassandra.sln && dotnet publish ./AspNetCore.Identity.Cassandra.sln -c Release -o ./obj/Docker/publish"
