version: '3.4'

services:

  identitysample.web:
    image: cassandra-sample/identitysample.web
    build:
      context: ./samples/IdentitySample.Web
      dockerfile: Dockerfile
    depends_on:
    - nosql.data

  nosql.data:
    image: cassandra